#!/usr/bin/env python3
"""mkbanks.py -- split Dragster across the FujiNet cartridge's banks.

A FujiNet bank is the 2K at $1000-$17FF; the 2K above it is the cartridge's
mailbox and the client owns only the tail inside it. Dragster is exactly 2048
bytes, so it fills a bank precisely and leaves nowhere for netcode -- which is
why it is split: the display kernel and its sprite data in one bank, the frame
logic and the transport in the other.

THE REGIONS COME FROM tools/dgmap.py AND THE ADDRESSES FROM THE ASSEMBLER'S OWN
LISTING, never from line numbers in this file. Every source line's address comes
out of build/dragster_org.lst, which `make verify-org` has just proved
reproduces the cartridge dump byte for byte.

EVERY BYTE KEEPS THE ADDRESS IT HAS TODAY, rebased $F000 -> $1000, and each bank
leaves the other's regions empty. That buys two things: every absolute JMP/JSR
target and every table address stays byte-identical, so check_patch.py can be a
real byte audit rather than a formality; and the holes a bank is left with are
exactly the regions it does not own, at addresses the map already knows.

ONE DIFFERENCE FROM COMBAT: a region's bank is a SET. Dragster has one code
region and three data regions that BOTH halves read, and they are emitted into
every bank that declares them, byte-identical. Combat had a single EXPORT of
addresses and no shared code at all -- it could not have had any, because a
bank switch is a jump and nothing returns through one, and here StageRace (game
bank) JMPs into the MIDDLE of PositionSprites and returns through its RTS to
StageRace's own caller.

Usage: mkbanks.py <stock.lst> <dragster.asm> <out.inc>
"""

import re
import sys

sys.path.insert(0, __file__.rsplit("/", 1)[0])
import dgmap
import patches as patchmap

REBASE = dgmap.ROM_BASE - dgmap.BANK_BASE

LST = re.compile(r"^\s*(\d+)/\s*([0-9A-F]{1,4}) :")
ORG = re.compile(r"^\s*ORG\b", re.IGNORECASE)
DIRECTIVE = re.compile(r"^\s*(CPU|INCLUDE)\b", re.IGNORECASE)


def line_addresses(path):
    """line number -> the address the assembler put that line at.

    Only top-level lines: an included file's lines carry a `(depth)` prefix and
    are deliberately not matched, because vcs.inc's equates are not Dragster.
    """
    addr = {}
    with open(path, errors="replace") as f:
        for line in f:
            m = LST.match(line)
            if m:
                addr.setdefault(int(m.group(1)), int(m.group(2), 16))
    return addr


def main():
    lst, src, out = sys.argv[1], sys.argv[2], sys.argv[3]
    addr = line_addresses(lst)
    lines = open(src).read().split("\n")

    probs = patchmap.selftest()
    if probs:
        for p in probs:
            print("mkbanks: patches: " + p, file=sys.stderr)
        return 1

    # Bucket every source line into the region its STOCK address falls in. A
    # comment line carries the address of the next byte to be emitted, so a
    # region banner groups with the code it introduces.
    buckets = {i: [] for i in range(len(dgmap.REGIONS))}
    pre = []
    for n, raw in enumerate(lines, 1):
        a = addr.get(n)
        if a is None:
            continue
        if a < dgmap.ROM_BASE:
            if not DIRECTIVE.match(raw):
                pre.append(raw)         # the zero-page equates
            continue
        if ORG.match(raw):
            continue                    # the generator emits each region's ORG
        for i, (lo, hi, _b, _k, _w) in enumerate(dgmap.REGIONS):
            if lo <= a < hi:
                buckets[i].append((a, raw))
                break

    # Patches are applied to a bucket, AFTER the split. That is why there is no
    # line-count rule here: a patch cannot misfile the lines after it, because
    # the filing already happened. It can only fail to fit in its own region,
    # which patches.apply_region asserts.
    for i, (lo, hi, _b, _k, _w) in enumerate(dgmap.REGIONS):
        buckets[i] = patchmap.apply_region(buckets[i], lo, hi)

    with open(out, "w") as f:
        f.write("; generated by tools/mkbanks.py -- do not edit.\n"
                "; Dragster, split across the FujiNet cartridge's banks. Every byte keeps\n"
                "; the address it has in the cartridge dump, rebased $F000 -> $1000.\n"
                "; Selected by DGBANK; see tools/dgmap.py for why the regions are what\n"
                "; they are, and tools/patches.py for every change made to the original.\n\n")
        f.write("\n".join(pre) + "\n")

        for i, (lo, hi, banks, kind, why) in enumerate(dgmap.REGIONS):
            if not banks:
                f.write("\n; $%04X-$%04X  neither bank: %s\n"
                        % (lo - REBASE, hi - 1 - REBASE, why))
                continue
            f.write("\n; --------------------------------------------------------------\n")
            f.write("; $%04X-$%04X  %s: %s\n"
                    % (lo - REBASE, hi - 1 - REBASE,
                       " and ".join(b.lower() + " bank" for b in sorted(banks)), why))
            if len(banks) > 1:
                f.write("; SHARED -- emitted into both banks, byte-identical.\n")
            for bank in sorted(banks):
                f.write("\tIF\tDGBANK = BANK%s\n" % bank)
                f.write("\tORG\t$%04X\n" % (lo - REBASE))
                for _a, text in buckets[i]:
                    f.write(text + "\n")
                # The region's end, so a bank file can ORG into the hole that
                # follows without a hardcoded address that goes stale the moment
                # a patch changes a region's length.
                f.write("DGRE%-4dEQU\t*\n" % i)
                f.write("\tIF\t* > $%04X\n" % (hi - REBASE))
                f.write("\tERROR\t\"region %d ($%04X-$%04X) has overrun its slot\"\n"
                        % (i, lo, hi - 1))
                f.write("\tENDIF\n")
                f.write("\tENDIF\n")

    sizes = {}
    for lo, hi, banks, _k, _w in dgmap.REGIONS:
        for b in banks:
            sizes[b] = sizes.get(b, 0) + hi - lo
    print("mkbanks: %s" % ", ".join("%s %d stock bytes (%d free)" % (b, n, 2048 - n)
                                    for b, n in sorted(sizes.items())))
    return 0


if __name__ == "__main__":
    sys.exit(main())
